### ISSUE TITLE
Use `main` branch instead of `master`

### ISSUE THREAD

**Issue by DeveloperWOW64** [SeaDevTeam/SDLauncher-UWP#16]
### ⏱️ Before you start...

- [X] I have checked whether a similar feature request has already been reported.

### 📄 Description

Current GitHub standard for branch usage is `main`. However, SeaDev uses `master`, which is no longer the standard.

**Comment by NoobNotFound** [comment]
ok I will after the NewCore, btw sorry for being 5 days late
